apiVersion: v1
kind: Service
metadata:
  labels:
    app: zuul-service-lb
    service: zuul-service-lb
  name: zuul-service-lb
  namespace: dev2
spec:
  ports:
    - name: tcp-8079-8079-zuul-service-lb
      protocol: TCP
      port: 8079
      targetPort: 8079
  selector:
    app: zuul-service
  type: LoadBalancer